name: Update README with Chess.com and LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Update README with latest Chess.com and LeetCode stats
        run: python fetch_chess_stats.py  # Runs the updated Python script

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add README.md
          git commit -m "Update README with latest Chess.com and LeetCode stats"
          git push "https://${{ secrets.PAT_TOKEN }}@github.com/matejpopovski/matejpopovski.git"
